site_name: Hello Nextflow
repo_url: https://github.com/Sydney-Informatics-Hub/hello-nextflow
repo_name: Sydney-Informatics-Hub/hello-nextflow

nav:
  - Home: index.md
  - Environment setup:
    - setup/index.md
  - Part 1:
    - 1.0 Introduction: part1/00_intro.md
    - 1.1 Why Nextflow?: part1/01_hellonextflow.md
    - 1.2 Hello World!: part1/02_helloworld.md
    - 1.3 Your first pipeline: part1/03_hellonf.md
    - 1.4 Outputs: part1/04_output.md
    - 1.5 Inputs: part1/05_inputs.md
    - 1.6 Parameters: part1/06_params.md
    - 1.7 Adding processes: part1/07_process.md
    - 1.8 Dynamic naming: part1/08_dynamic.md
  - Part 2:
    - 2.0 Introduction: part2/00_intro.md
    - 2.1 Our first process and container: part2/01_salmon_idx.md
    - 2.2 Samplesheets, operators, and groovy: part2/02_fastqc.md
    - 2.3 Multiple process inputs: part2/03_quant.md
    - 2.4 Combining channels, multiple process outputs: part2/04_multiqc.md
    - 2.5 Upscaling to multiple samples and introspection: part2/05_scale.md

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
